version: '3.8'

services:
  freqtrade-bot:
    build: .
    container_name: okx-scalping-bot
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./strategies:/app/strategies
      - ./backtest:/app/backtest
      - ./data:/app/data
    restart: unless-stopped
    network_mode: host
